### ISSUE TITLE
Add parameters for chatgpt deployment capacity and sku name

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/agent-openai-java-banking-assistant#8]
To allow for easier use by developers who have quota restrictions, could you add azd env parameters in main.parameters.json for capacity (integer, default to 30) and skuname (string, default to either Standard or GlobalStandard)?

https://github.com/Azure-Samples/agent-openai-java-banking-assistant/blob/main/infra/main.bicep#L56
https://github.com/Azure-Samples/agent-openai-java-banking-assistant/blob/98e8dad88e730764f4eb8bbd956f47d898791aa9/infra/main.bicep#L283

Example:
https://github.com/Azure-Samples/openai-chat-app-quickstart/blob/7d90b9820d3f765cbb3411fae8c7624e521c42f8/infra/main.parameters.json#L32

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by dantelmomsft** [comment]
@pamelafox  capacity parameter was already there in bicep ( but not in params file). Added both in params and bicep file.

**Comment by pamelafox** [comment]
Thanks Davide!
